Algoritmo "atividade8"

var
   cor: caractere
inicio
   escreval("as cores são verde, azul, amarelo, vermelho")
   escreva("Digite a cor do CD: ")
   leia(cor)

se cor = "verde" entao
    escreva("Preço: 10 reais")
fimse

se cor = "azul" entao
    escreva("Preço: 20 reais")
fimse

se cor = "amarelo" entao
    escreva("Preço: 30 reais")
fimse

se cor = "vermelho" entao
    escreva("Preço: 40 reais")
fimse

fimalgoritmo