Algoritmo "Aula"

Var
n1, n2, soma, subtracao, multiplicacao: real


Inicio
  escreva("Me diga um número: ")
  leia(n1)

  escreva("Me diga outro número: ")
  leia(n2)

  limpatela

  soma <- n1 + n2
  subtracao <- n1 - n2
  multiplicacao <- n1 * n2

  escreva("Soma: ", soma)
 escreval
  escreva("Subtração: ", subtracao)
 escreval
  escreva("Multiplicação: ", multiplicacao)

Fimalgoritmo